/**
 * @file parse.js
 * @author scott.mcgowan@wisemonkeygames.com
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status = require('@converseai/plugins-sdk').Status;
const ExternalResponse = require('@converseai/plugins-sdk').Payloads.ExternalFunctionResponse;
const ParseExpression = require('die-roller').parse;

module.exports = function parse(app, body) {

  var response = new ExternalResponse();

  response.setBody(ParseExpression(body.payload.queryParam.expression.data[0]));

  app.send(Status.SUCCESS, response);
};
