/**
 * @file plugins.js
 * @name smcgowan_die_roller_plugin
 * @description  
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 *
 * IMPORTANT: THIS FILE IS AUTO GENERATED, CHANGES MAY BE OVERRIDDEN!
 */

'use strict';
const ConversePluginsSDK = require('@converseai/plugins-sdk');

/**
 * smcgowan_die_roller_plugin plugin. To be used with
 * Converse AI Plugins SDK.
 *
 * @example
 * const converseai  = require('plugins.js');
 * const express     = require('express');
 * const bodyParser  = require('body-parser');
 *
 * var server = express();
 *
 * server.use(bodyParser.json());
 * server.post('/', function (req, res) {
 *    converseai.smcgowan_die_roller_plugin(req, res);
 * });
 *
 * @param {Object} request Express HTTP request object.
 * @param {Object} response Express HTTP response object.
 */
exports.smcgowan_die_roller_plugin = function (request, response) {
  var app = new ConversePluginsSDK.http({ request, response });

  if (request && request.headers && request.headers['x_converse_app_token'] && request.headers['x_converse_app_token'] === require('./app-token')) {

    app.setModules({
      parse_expression: require('./converseai_modules/parse_expression')
    });

    app.setExternal({
      parse: require('./converseai_externals/parse')
    });


    app.handleRequest();
  } else {
    app._handleError(403, 'FORBIDDEN_APP_TOKEN', 'Forbidden app token set.');
  }
};
