/**
 * @file parse_expression.js
 * @author scott.mcgowan@wisemonkeygames.com
 * @description  
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status = require('@converseai/plugins-sdk').Status;
const ModuleResponse = require('@converseai/plugins-sdk').Payloads.Module.ModuleResponse;
const ParseExpression = require('die-roller').parse;

module.exports = function parse_expression(app, body) {

  var expression = body.payload.moduleParam.expression;

  if (expression === undefined) {
    app.fail({ httpStatus: 400, code: 'REQUIRED_PARAMS_UNDEFINED', description: 'Required parameter "expression" is undefined.' });
    return;
  }

  var response = new ModuleResponse();
  response.setValue(ParseExpression(expression));
  app.send(Status.SUCCESS, response);
};
